### ISSUE TITLE
Generation of report failed: FileNotFoundException: bugreport_out/data/../raw/087-/data_USAGE

### ISSUE THREAD

**Issue by regisd** [sonyxperiadev/ChkBugReport#14]
I ran
    java -jar chkbugreport-0.5-211.jar bugreport.txt

And it failed with

> Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.charteditor.ChartEditorPlugin...
> Collecting errors...
> Copying extra resources...
> Saving raw sections
> java.io.FileNotFoundException: bugreport_out/data/../raw/087-/data_USAGE (No such file or directory)
> 	at java.io.FileOutputStream.open0(Native Method)
> 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
> 	at com.sonyericsson.chkbugreport.Module.saveSections(Module.java:706)
> 	at com.sonyericsson.chkbugreport.Module.generate(Module.java:566)
> 	at com.sonyericsson.chkbugreport.Main.run(Main.java:232)
> 	at com.sonyericsson.chkbugreport.Main.main(Main.java:358)

**Comment by regisd** [comment]
This is simply due to the fact that a Unix filename cannot contain `/`, but the section title has one:

> ------ /data USAGE: directory (/system/xbin/su root du -d1 -m /data) ------

**Comment by space2** [comment]
Thanks for reporting it! I'll look into it.

**Comment by regisd** [comment]
The fix is trivial, I've a pending change. I'll send it as soon as I've received approval from the open-source reviewer.
