### ISSUE TITLE
Replace ant by a modern build system

### ISSUE THREAD

**Issue by regisd** [sonyxperiadev/ChkBugReport#16]
It would be easier for third-party developers to have a build manager (e.g. Maven).

**Comment by regisd** [comment]
I can add Maven or Gradle, whatever you prefer.

**Comment by space2** [comment]
I prefer Gradle, since that seems to be the new standard in Android as well.

**Comment by regisd** [comment]
I just realized the project is actually build by Apache ant.

**Comment by space2** [comment]
No problem. If you prefer Gradle, feel free to add a gradle build script to it as well.

**Comment by colymore** [comment]
I will start with this. :)
