### ISSUE TITLE
Wakelocks Plugin Issue

### ISSUE THREAD

**Issue by ionestel** [sonyxperiadev/ChkBugReport#18]
I'm using v0.5 (rel 203). It appears that it requires loading `com.sonyericsson.chkbugreport.plugins.battery.WakelocksPlugin` in order to generate the battery stats.

I've been getting the following error when I execute `java -jar chkbugreport.jar bugreport.txt`:

> Plugin crashed while loading data: com.sonyericsson.chkbugreport.plugins.battery.WakelocksPlugin

All the other plugins seemed to have been loaded properly.

**Comment by space2** [comment]
Could you attach the bugreport file?

**Comment by jhprks** [comment]
Please see the attached for bugreport.txt and the output from running the command.

[bugreport.txt](https://github.com/sonyxperiadev/ChkBugReport/files/149146/bugreport.txt)

[bugreport_out.zip](https://github.com/sonyxperiadev/ChkBugReport/files/149148/bugreport_out.zip)

**Comment by space2** [comment]
Hi!

Thanks for the files. I couldn't reproduce the issue with the latest version. I uploaded a new precompiled binary (rel 215), can you test with it?
(http://sonyxperiadev.github.com/ChkBugReport/download/chkbugreport-0.5-215.jar)

**Comment by jhprks** [comment]
Thanks! I tried rel215 and it's no longer showing me the "plugin crashed" message and I can see the battery info.
