### ISSUE TITLE
Need help - Google Pixel Android N 7.1.1 bugreport not read properly with chkbugreport 

### ISSUE THREAD

**Issue by himanshulak** [sonyxperiadev/ChkBugReport#26]
Hello,

I am looking in to this Pixel bugreport and a similar other QC product and having issues with generating the report with the chkbugreport tool.

When the Pixel device(Android 7.1.1) bug report is parsed the index.html file is not generated.
Analysis gives error inbetween as below.., though if needed please let me know I would share the logs.

###################ERROR_LOGS################

C:\Projects\Tools>java -jar chkbugreport-0.4-185.jar pixelbugreport.txt
java.lang.ClassNotFoundException: com.apple.eawt.Application
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.sonyericsson.chkbugreport.Main.changeDocIcon(Main.java:112)
        at com.sonyericsson.chkbugreport.Main.<init>(Main.java:96)
        at com.sonyericsson.chkbugreport.Main.main(Main.java:593)
Failed to register extension 'com.sonyericsson.chkbugreport.AdbExtension' due to: java.lang.NoClassDefFoundError: com/android/ddmlib/IShellOutputReceiver
ChkBugReport 0.4 (rev 185) (C) 2012 Sony Ericsson Mobile Communications AB
Loading input...
Could not find header in ps output
Cannot find section: PROCESSES (ignoring it)
Plugins are loading data...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.SysPropsPlugin...
[SysPropsPlugin]Cannot parse uptime:  15:53:27 up 21:18,  0 users,  load average: 7.57, 6.10, 5.72
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.PackageInfoPlugin...
[PackageInfoPlugin]Cannot find section: PACKAGE SETTINGS
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.ScreenShotPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.stacktrace.StackTracePlugin...
java.lang.NumberFormatException: For input string: "com.google.android.gms:17"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at com.sonyericsson.chkbugreport.plugins.stacktrace.StackTraceScanner.scan(StackTraceScanner.java:146)
        at com.sonyericsson.chkbugreport.plugins.stacktrace.StackTracePlugin.run(StackTracePlugin.java:126)
        at com.sonyericsson.chkbugreport.plugins.stacktrace.StackTracePlugin.run(StackTracePlugin.java:120)
        at com.sonyericsson.chkbugreport.plugins.stacktrace.StackTracePlugin.load(StackTracePlugin.java:83)
        at com.sonyericsson.chkbugreport.Module.runPlugins(Module.java:543)
        at com.sonyericsson.chkbugreport.Module.generate(Module.java:472)
        at com.sonyericsson.chkbugreport.Main.processFile(Main.java:277)
        at com.sonyericsson.chkbugreport.Main.loadFile(Main.java:266)
        at com.sonyericsson.chkbugreport.Main.run(Main.java:248)
        at com.sonyericsson.chkbugreport.Main.main(Main.java:593)
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.MemPlugin...
[MemPlugin]Section not found: DUMP OF SERVICE meminfo (ignoring section)
[MemPlugin]librank section is suspiciously small... ignoring it
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.logs.SystemLogPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.logs.MainLogPlugin...
[LogPlugin]Cannot find section MAIN LOG (aborting plugin)
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.logs.kernel.KernelLogPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.logs.event.EventLogPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.ftrace.FTracePlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.SurfaceFlingerPlugin...
[SurfaceFlingerPlugin]Error parsing: cannot recognize section!
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.WindowManagerPlugin...
Cannot find node 'Event Hub State:'
java.lang.NullPointerException
        at com.sonyericsson.chkbugreport.util.Util.parseBoolean(Util.java:366)
        at com.sonyericsson.chkbugreport.plugins.WindowManagerPlugin.loadWindowManagerState(WindowManagerPlugin.java:189)
        at com.sonyericsson.chkbugreport.plugins.WindowManagerPlugin.load(WindowManagerPlugin.java:96)
        at com.sonyericsson.chkbugreport.Module.runPlugins(Module.java:543)
        at com.sonyericsson.chkbugreport.Module.generate(Module.java:472)
        at com.sonyericsson.chkbugreport.Main.processFile(Main.java:277)
        at com.sonyericsson.chkbugreport.Main.loadFile(Main.java:266)
        at com.sonyericsson.chkbugreport.Main.run(Main.java:248)
        at com.sonyericsson.chkbugreport.Main.main(Main.java:593)
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.CpuFreqPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.battery.BatteryInfoPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.WakelocksPlugin...
[WakelocksPlugin]Section not found: KERNEL WAKELOCKS (aborting plugin)
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.AlarmManagerPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.UsageHistoryPlugin...
[UsageHistoryPlugin]Cannot find section: USAGE HISTORY
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.PSTreePlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.MiscPlugin...
Running (load) plugin: com.sonyericsson.chkbugreport.plugins.SummaryPlugin...
Plugins are generating output...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.SysPropsPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.PackageInfoPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.ScreenShotPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.MemPlugin...
[MemPlugin]procrank section is suspiciously small... ignoring it
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.logs.SystemLogPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.logs.MainLogPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.logs.kernel.KernelLogPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.logs.event.EventLogPlugin...
ComponentStat: onResume was missing (63636851)
ComponentStat: onCreate was missing (63636851)
ComponentStat: onCreate was called again without onDestroy (90)
ComponentStat: onResume was missing (6165789)
ComponentStat: onCreate was missing (6165789)
ComponentStat: onResume was missing (179030741)
ComponentStat: onCreate was missing (179030741)
ComponentStat: onCreate was missing (78)
ComponentStat: onResume was missing (77232840)
ComponentStat: onCreate was missing (77232840)
ComponentStat: onCreate was called again without onDestroy (91)
ComponentStat: onResume was missing (60193920)
ComponentStat: onCreate was missing (60193920)
ComponentStat: onResume was missing (68741941)
ComponentStat: onCreate was missing (68741941)
ComponentStat: onResume was already guessed, but it's missing again (60193920)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onCreate was missing (91)
ComponentStat: onCreate was missing (89)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onCreate was called again without onDestroy (89)
ComponentStat: onResume was missing (60373270)
ComponentStat: onCreate was missing (60373270)
ComponentStat: onResume was missing (121117689)
ComponentStat: onCreate was missing (121117689)
ComponentStat: onResume was called again without onPause (89)
ComponentStat: onResume was already guessed, but it's missing again (60373270)
ComponentStat: onCreate was called again without onDestroy (89)
ComponentStat: onResume was missing (23044084)
ComponentStat: onCreate was missing (23044084)
ComponentStat: onCreate was called again without onDestroy (89)
ComponentStat: onResume was missing (119450726)
ComponentStat: onCreate was missing (119450726)
ComponentStat: onCreate was called again without onDestroy (89)
ComponentStat: onResume was missing (15749034)
ComponentStat: onCreate was missing (15749034)
ComponentStat: onResume was missing (160692058)
ComponentStat: onCreate was missing (160692058)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onCreate was missing (85)
ComponentStat: onResume was missing (267100170)
ComponentStat: onCreate was missing (267100170)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onResume was called again without onPause (89)
ComponentStat: onCreate was called again without onDestroy (89)
ComponentStat: onResume was already guessed, but it's missing again (160692058)
ComponentStat: onCreate was called again without onDestroy (89)
ComponentStat: onResume was missing (115331678)
ComponentStat: onCreate was missing (115331678)
ComponentStat: onResume was missing (114472554)
ComponentStat: onCreate was missing (114472554)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onResume was called again without onPause (89)
ComponentStat: onResume was already guessed, but it's missing again (160692058)
ComponentStat: onResume was called again without onPause (89)
ComponentStat: onResume was already guessed, but it's missing again (119450726)
ComponentStat: onResume was called again without onPause (89)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onResume was already guessed, but it's missing again (23044084)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onResume was called again without onPause (89)
ComponentStat: onResume was already guessed, but it's missing again (60373270)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onCreate was called again without onDestroy (92)
ComponentStat: onResume was missing (209859621)
ComponentStat: onCreate was missing (209859621)
ComponentStat: onResume was missing (264977609)
ComponentStat: onCreate was missing (264977609)
ComponentStat: onResume was already guessed, but it's missing again (209859621)
ComponentStat: onCreate was called again without onDestroy (92)
ComponentStat: onResume was missing (245388294)
ComponentStat: onCreate was missing (245388294)
ComponentStat: onResume was missing (109452662)
ComponentStat: onCreate was missing (109452662)
ComponentStat: onResume was missing (5869436)
ComponentStat: onCreate was missing (5869436)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onCreate was called again without onDestroy (94)
ComponentStat: onResume was missing (216376136)
ComponentStat: onCreate was missing (216376136)
ComponentStat: onResume was missing (182093919)
ComponentStat: onCreate was missing (182093919)
ComponentStat: onResume was already guessed, but it's missing again (216376136)
ComponentStat: onResume was missing (234722498)
ComponentStat: onCreate was missing (234722498)
ComponentStat: onResume was already guessed, but it's missing again (216376136)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was already guessed, but it's missing again (245388294)
ComponentStat: onCreate was missing (92)
ComponentStat: onResume was already guessed, but it's missing again (209859621)
ComponentStat: onCreate was called again without onDestroy (92)
ComponentStat: onResume was missing (164557322)
ComponentStat: onCreate was missing (164557322)
ComponentStat: onResume was missing (251044081)
ComponentStat: onCreate was missing (251044081)
ComponentStat: onResume was missing (159653832)
ComponentStat: onCreate was missing (159653832)
ComponentStat: onResume was called again without onPause (92)
ComponentStat: onResume was already guessed, but it's missing again (251044081)
ComponentStat: onCreate was already guessed, but it's missing again (92)
ComponentStat: onResume was called again without onPause (92)
ComponentStat: onResume was already guessed, but it's missing again (209859621)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onCreate was already guessed, but it's missing again (92)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was missing (87298382)
ComponentStat: onCreate was missing (87298382)
ComponentStat: onResume was already guessed, but it's missing again (87298382)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onCreate was called again without onDestroy (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was missing (145150606)
ComponentStat: onCreate was missing (145150606)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was missing (37272910)
ComponentStat: onCreate was missing (37272910)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was missing (68640786)
ComponentStat: onCreate was missing (68640786)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was already guessed, but it's missing again (60373270)
ComponentStat: onResume was missing (88373500)
ComponentStat: onCreate was missing (88373500)
ComponentStat: onCreate was already guessed, but it's missing again (78)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was missing (206284496)
ComponentStat: onCreate was missing (206284496)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was missing (87918813)
ComponentStat: onCreate was missing (87918813)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was missing (2385681)
ComponentStat: onCreate was missing (2385681)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was missing (240314704)
ComponentStat: onCreate was missing (240314704)
ComponentStat: onCreate was missing (88)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onResume was missing (221577470)
ComponentStat: onCreate was missing (221577470)
ComponentStat: onResume was missing (267964734)
ComponentStat: onCreate was missing (267964734)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was missing (184609790)
ComponentStat: onCreate was missing (184609790)
ComponentStat: onResume was missing (12280190)
ComponentStat: onCreate was missing (12280190)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was already guessed, but it's missing again (184609790)
ComponentStat: onResume was missing (6454574)
ComponentStat: onCreate was missing (6454574)
ComponentStat: onResume was called again without onPause (88)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onResume was already guessed, but it's missing again (206284496)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was missing (232024266)
ComponentStat: onCreate was missing (232024266)
ComponentStat: onResume was missing (120273927)
ComponentStat: onCreate was missing (120273927)
ComponentStat: onResume was called again without onPause (88)
ComponentStat: onResume was already guessed, but it's missing again (232024266)
ComponentStat: onResume was called again without onPause (88)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onResume was already guessed, but it's missing again (206284496)
ComponentStat: onCreate was called again without onDestroy (88)
ComponentStat: onResume was missing (266216875)
ComponentStat: onCreate was missing (266216875)
ComponentStat: onResume was missing (154511076)
ComponentStat: onCreate was missing (154511076)
ComponentStat: onResume was called again without onPause (88)
ComponentStat: onResume was already guessed, but it's missing again (266216875)
ComponentStat: onResume was called again without onPause (88)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onResume was already guessed, but it's missing again (206284496)
ComponentStat: onCreate was called again without onDestroy (96)
ComponentStat: onResume was missing (183804273)
ComponentStat: onCreate was missing (183804273)
ComponentStat: onResume was missing (216889636)
ComponentStat: onCreate was missing (216889636)
ComponentStat: onCreate was called again without onDestroy (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was missing (72762023)
ComponentStat: onCreate was missing (72762023)
ComponentStat: onCreate was missing (96)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was already guessed, but it's missing again (267100170)
ComponentStat: onResume was missing (260598716)
ComponentStat: onCreate was missing (260598716)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (85)
ComponentStat: onResume was already guessed, but it's missing again (267100170)
ComponentStat: onCreate was already guessed, but it's missing again (96)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (85)
ComponentStat: onResume was already guessed, but it's missing again (267100170)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (85)
ComponentStat: onResume was already guessed, but it's missing again (267100170)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (85)
ComponentStat: onResume was already guessed, but it's missing again (267100170)
ComponentStat: onResume was already guessed, but it's missing again (206284496)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onCreate was already guessed, but it's missing again (88)
ComponentStat: onResume was called again without onPause (88)
ComponentStat: onResume was already guessed, but it's missing again (206284496)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was called again without onPause (85)
ComponentStat: onCreate was already guessed, but it's missing again (89)
ComponentStat: onCreate was missing (94)
ComponentStat: onCreate was missing (90)
ComponentStat: onCreate was already guessed, but it's missing again (90)
ComponentStat: onCreate was already guessed, but it's missing again (90)
ComponentStat: onCreate was missing (86)
ComponentStat: onResume was already guessed, but it's missing again (267100170)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onCreate was called again without onDestroy (96)
ComponentStat: onResume was already guessed, but it's missing again (183804273)
ComponentStat: onResume was missing (122264348)
ComponentStat: onCreate was missing (122264348)
ComponentStat: onResume was called again without onPause (96)
ComponentStat: onResume was already guessed, but it's missing again (122264348)
ComponentStat: onResume was called again without onPause (78)
ComponentStat: onResume was already guessed, but it's missing again (77232840)
ComponentStat: onCreate was called again without onDestroy (97)
ComponentStat: onResume was missing (86269837)
ComponentStat: onCreate was missing (86269837)
ComponentStat: onResume was missing (46132485)
ComponentStat: onCreate was missing (46132485)
ComponentStat: onResume was already guessed, but it's missing again (86269837)
ComponentStat: onResume was missing (8192974)
ComponentStat: onCreate was missing (8192974)
ComponentStat: onResume was missing (172014999)
ComponentStat: onCreate was missing (172014999)
ComponentStat: onResume was called again without onPause (97)
ComponentStat: onResume was already guessed, but it's missing again (8192974)
ComponentStat: onResume was missing (15485083)
ComponentStat: onCreate was missing (15485083)
ComponentStat: onResume was called again without onPause (97)
ComponentStat: onResume was already guessed, but it's missing again (8192974)
ComponentStat: onResume was missing (125349898)
ComponentStat: onCreate was missing (125349898)
ComponentStat: onResume was called again without onPause (97)
Cannot make DB connection: java.lang.ClassNotFoundException: org.sqlite.JDBC
ProcStat: am_proc_start was missing (7362 @ 05-10 09:47:17.314)
ProcStat: am_proc_start was missing (5133 @ 05-10 09:48:11.048)
ProcStat: am_proc_start was missing (7726 @ 05-10 09:49:15.151)
ProcStat: am_proc_start without am_died (10018 @ 05-10 09:49:16.085)
ProcStat: am_proc_start without am_died (10018 @ 05-10 09:49:19.358)
ProcStat: am_proc_start was missing (7069 @ 05-10 09:49:27.698)
ProcStat: am_proc_start was missing (8085 @ 05-10 09:49:30.304)
ProcStat: am_proc_start was missing (8302 @ 05-10 09:49:38.899)
ProcStat: am_proc_start was missing (7288 @ 05-10 09:49:45.774)
ProcStat: am_proc_start was missing (8346 @ 05-10 09:49:45.775)
ProcStat: am_proc_start was missing (8377 @ 05-10 09:51:59.995)
ProcStat: am_proc_start was missing (2122 @ 05-10 09:58:58.941)
ProcStat: am_proc_start was missing (7825 @ 05-10 09:59:35.701)
ProcStat: am_proc_start was missing (5154 @ 05-10 10:08:00.009)
ProcStat: am_proc_start was missing (8700 @ 05-10 10:08:01.180)
ProcStat: am_proc_start was missing (7788 @ 05-10 10:09:25.649)
ProcStat: am_proc_start was missing (8825 @ 05-10 10:09:25.651)
ProcStat: am_proc_start was missing (8924 @ 05-10 10:21:58.757)
ProcStat: am_proc_start was missing (7629 @ 05-10 10:21:58.759)
ProcStat: am_proc_start was missing (7315 @ 05-10 10:21:58.763)
ProcStat: am_proc_start was missing (8178 @ 05-10 10:21:58.766)
ProcStat: am_proc_start was missing (8807 @ 05-10 10:21:58.768)
ProcStat: am_proc_start was missing (8626 @ 05-10 10:22:59.560)
ProcStat: am_proc_start was missing (9389 @ 05-10 10:39:22.343)
ProcStat: am_proc_start without am_died (10108 @ 05-10 11:15:58.177)
ProcStat: am_proc_start was missing (8513 @ 05-10 11:19:58.964)
ProcStat: am_proc_start without am_died (10018 @ 05-10 11:40:53.832)
ProcStat: am_proc_start was missing (2422 @ 05-10 11:42:16.489)
ProcStat: am_proc_start was missing (8725 @ 05-10 11:42:45.995)
ProcStat: am_proc_start without am_died (10103 @ 05-10 11:44:16.128)
ProcStat: am_proc_start was missing (9007 @ 05-10 11:44:38.466)
ProcStat: am_proc_start was missing (8745 @ 05-10 12:15:50.728)
ProcStat: am_proc_start was missing (9486 @ 05-10 12:16:16.748)
ProcStat: am_proc_start without am_died (10035 @ 05-10 12:16:25.031)
ProcStat: am_proc_start without am_died (10018 @ 05-10 12:16:25.871)
ProcStat: am_proc_start without am_died (10069 @ 05-10 12:17:06.008)
ProcStat: am_proc_start without am_died (10098 @ 05-10 12:17:06.214)
ProcStat: am_proc_start without am_died (10062 @ 05-10 12:17:07.169)
ProcStat: am_proc_start was missing (9953 @ 05-10 12:17:07.202)
ProcStat: am_proc_start without am_died (10018 @ 05-10 12:17:07.432)
ProcStat: am_proc_start without am_died (10108 @ 05-10 12:17:07.878)
ProcStat: am_proc_start without am_died (10090 @ 05-10 12:17:17.997)
ProcStat: am_proc_start was missing (10431 @ 05-10 12:17:20.789)
ProcStat: am_proc_start was missing (10562 @ 05-10 12:17:26.642)
ProcStat: am_proc_start was missing (10641 @ 05-10 12:17:27.161)
ProcStat: am_proc_start was missing (11161 @ 05-10 12:17:28.883)
ProcStat: am_proc_start was missing (11133 @ 05-10 12:17:33.807)
ProcStat: am_proc_start was missing (10220 @ 05-10 12:17:35.759)
ProcStat: am_proc_start without am_died (10031 @ 05-10 12:17:47.563)
ProcStat: am_proc_start was missing (11207 @ 05-10 12:17:47.817)
ProcStat: am_proc_start was missing (11051 @ 05-10 12:17:47.875)
ProcStat: am_proc_start was missing (11494 @ 05-10 12:17:48.693)
ProcStat: am_proc_start was missing (10727 @ 05-10 12:18:08.860)
ProcStat: am_proc_start was missing (11558 @ 05-10 12:18:15.312)
ProcStat: am_proc_start was missing (10042 @ 05-10 12:18:37.877)
ProcStat: am_proc_start was missing (11527 @ 05-10 12:18:42.248)
ProcStat: am_proc_start was missing (10852 @ 05-10 12:27:15.650)
ProcStat: am_proc_start without am_died (10018 @ 05-10 12:30:06.540)
ProcStat: am_proc_start was missing (9460 @ 05-10 12:30:36.855)
ProcStat: am_proc_start was missing (10669 @ 05-10 12:31:14.820)
ProcStat: am_proc_start was missing (11586 @ 05-10 12:31:15.920)
ProcStat: am_proc_start was missing (2756 @ 05-10 12:31:15.922)
ProcStat: am_proc_start was missing (8285 @ 05-10 12:31:16.321)
ProcStat: am_proc_start was missing (9205 @ 05-10 12:31:16.745)
ProcStat: am_proc_start without am_died (10090 @ 05-10 12:31:16.951)
ProcStat: am_proc_start was missing (11028 @ 05-10 12:31:17.044)
ProcStat: am_proc_start was missing (7517 @ 05-10 12:31:17.075)
ProcStat: am_proc_start was missing (8150 @ 05-10 12:31:17.212)
ProcStat: am_proc_start was missing (6044 @ 05-10 12:31:17.410)
ProcStat: am_proc_start was missing (11239 @ 05-10 12:47:32.064)
ProcStat: am_proc_start was missing (10135 @ 05-10 12:47:32.068)
ProcStat: am_proc_start was missing (11192 @ 05-10 12:47:55.442)
ProcStat: am_proc_start was missing (10905 @ 05-10 12:47:55.444)
ProcStat: am_proc_start was missing (11086 @ 05-10 12:47:55.445)
ProcStat: am_proc_start was missing (7139 @ 05-10 12:49:10.247)
ProcStat: am_proc_start was missing (10885 @ 05-10 12:49:10.250)
ProcStat: am_proc_start was missing (11331 @ 05-10 13:59:28.223)
ProcStat: am_proc_start without am_died (10108 @ 05-10 15:51:24.185)
ProcStat: am_proc_start without am_died (10088 @ 05-10 15:51:45.460)
ProcStat: am_proc_start was missing (11895 @ 05-10 15:51:45.685)
ProcStat: am_proc_start without am_died (10103 @ 05-10 15:51:45.815)
ProcStat: am_proc_start was missing (10949 @ 05-10 15:51:46.058)
ProcStat: am_proc_start was missing (11913 @ 05-10 15:51:47.431)
ProcStat: am_proc_start without am_died (10006 @ 05-10 15:51:48.764)
ProcStat: am_proc_start without am_died (10093 @ 05-10 15:51:48.915)
ProcStat: am_proc_start without am_died (10035 @ 05-10 15:51:51.378)
ProcStat: am_proc_start without am_died (10018 @ 05-10 15:51:51.652)
ProcStat: am_proc_start without am_died (10011 @ 05-10 15:51:53.727)
ProcStat: am_proc_start without am_died (1000 @ 05-10 15:52:09.840)
ProcStat: am_proc_start without am_died (10002 @ 05-10 15:52:09.996)
ProcStat: am_proc_start without am_died (10047 @ 05-10 15:52:10.219)
ProcStat: am_proc_start without am_died (10026 @ 05-10 15:52:10.393)
ProcStat: am_proc_start without am_died (10062 @ 05-10 15:52:10.477)
ProcStat: am_proc_start without am_died (10098 @ 05-10 15:52:10.727)
ProcStat: am_proc_start was missing (7961 @ 05-10 15:52:19.107)
ProcStat: am_proc_start was missing (7802 @ 05-10 15:52:21.252)
ProcStat: am_proc_start was missing (12469 @ 05-10 15:52:31.419)
ProcStat: am_proc_start was missing (12738 @ 05-10 15:52:36.375)
ProcStat: am_proc_start without am_died (10103 @ 05-10 15:52:37.119)
ProcStat: am_proc_start without am_died (10112 @ 05-10 15:52:48.854)
ProcStat: am_proc_start was missing (5968 @ 05-10 15:53:03.828)
ProcStat: am_proc_start was missing (12630 @ 05-10 15:53:03.971)
ProcStat: am_proc_start was missing (12885 @ 05-10 15:53:09.484)
ProcStat: am_proc_start was missing (12977 @ 05-10 15:53:14.675)
ProcStat: am_proc_start was missing (13281 @ 05-10 15:53:27.618)
ProcStat: am_proc_start was missing (12129 @ 05-10 15:53:27.619)
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.ftrace.FTracePlugin...
[FTracePlugin]Cannot find section: FTRACE
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.SurfaceFlingerPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.CpuFreqPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.battery.BatteryInfoPlugin...
[BatteryInfoPlugin]Section not found: DUMP OF SERVICE batteryinfo (ignoring it)
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.WakelocksPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.AlarmManagerPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.UsageHistoryPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.PSTreePlugin...
[PSTreePlugin]Process list information not found! (aborting plugin)
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.MiscPlugin...
Running (generate) plugin: com.sonyericsson.chkbugreport.plugins.SummaryPlugin...
Collecting errors...
Copying extra resources...
Saving raw sections
java.io.FileNotFoundException: C:\Projects\pixelbugreport_out\data\..\raw\1241-_com.android.settings\com.android.set[...]Settings$DevelopmentSettin
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at com.sonyericsson.chkbugreport.Module.saveSections(Module.java:599)
        at com.sonyericsson.chkbugreport.Module.generate(Module.java:484)
        at com.sonyericsson.chkbugreport.Main.processFile(Main.java:277)
        at com.sonyericsson.chkbugreport.Main.loadFile(Main.java:266)
        at com.sonyericsson.chkbugreport.Main.run(Main.java:248)
        at com.sonyericsson.chkbugreport.Main.main(Main.java:593)

**Comment by onlinesen** [comment]
The same issue.
Any help?

**Comment by helloxm** [comment]
I also has this problem in android 5.1.1

**Comment by toshi38-sony** [comment]
Hey, thanks for reaching out, sadly this tool hasn't been maintained very much for the last few years.

We've started to look at updating this tool again; however, we're just looking at fixing issues for Android 10 (and newer).

I'm going to go ahead and close this issue, if you can reproduce with a bugreport from an android 10 or newer OS build please re-open or create a new issue!
