### ISSUE TITLE
java.lang.ClassNotFoundException com.sonyericsson.chkbugreport.AdbExtension

### ISSUE THREAD

**Issue by wcypierre** [sonyxperiadev/ChkBugReport#3]
Test Environment:
- Ubuntu 12.04
- OpenJDK 1.6.0_24
- Used the v0.4 rev 185 precompiled jar

The error message appeared during the start up but it doesn't seem to affect the execution of the program(the parsed logs are still generated)

Error Message:
java.lang.ClassNotFoundException: com.apple.eawt.Application
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:186)
    at com.sonyericsson.chkbugreport.Main.changeDocIcon(Main.java:112)
    at com.sonyericsson.chkbugreport.Main.<init>(Main.java:96)
    at com.sonyericsson.chkbugreport.Main.main(Main.java:593)
Failed to register extension 'com.sonyericsson.chkbugreport.AdbExtension' due to: java.lang.NoClassDefFoundError: com/android/ddmlib/IShellOutputReceiver

**Comment by space2** [comment]
Hi!

Sorry for the late reply, it was a busy vacation.

The problem is that the bugreport file contains some extra lines at the beginning ("try again in 1second" repeated a couple if times). AFAIR, chkbugreport can ignore up to 3 garbage lines at the beginning, but in this case there are about 10. To fix it, just delete the these lines from the beginning of the file.

**Comment by felipeaugusto1** [comment]
WOW! Nice. It's working now. Thanks

**Comment by jithu232** [comment]
Failed to register extension 'com.sonyericsson.chkbugreport.AdbExtension' due to: java.lang.NoClassDefFoundError: com/android/ddmlib/IShellOutputReceiver
ChkBugReport 0.4 (rev 185) (C) 2012 Sony Ericsson Mobile Communications AB
Loading input...
java.io.IOException: Does not look like a bugreport file!
	at com.sonyericsson.chkbugreport.BugReportModule.load(BugReportModule.java:248)
	at com.sonyericsson.chkbugreport.BugReportModule.load(BugReportModule.java:129)
	at com.sonyericsson.chkbugreport.Main.loadFrom(Main.java:378)
	at com.sonyericsson.chkbugreport.Main.loadReportFrom(Main.java:353)
	at com.sonyericsson.chkbugreport.Main.loadFile(Main.java:261)
	at com.sonyericsson.chkbugreport.Main.run(Main.java:248)
	at com.sonyericsson.chkbugreport.Main.main(Main.java:593)

**Comment by space2** [comment]
This happens usually if there are some extra lines at the beginning of the bugreport. ChkBugReport can ignore up to 3 lines, but if there are more, it gives up.
If you send the bugreport file, I can take a look at it.

**Comment by jithu232** [comment]
Here it is:https://www.dropbox.com/s/aydrkf6vu0ohyuk/405_1807_2015-02-12_21-20-35.txt

**Comment by jithu232** [comment]
Hi,
Please help me, i got lot off bug report from client.

**Comment by space2** [comment]
Hi!

Unfortunately I don't recognize this format. Which application was used to save this bugreport?

**Comment by jithu232** [comment]
org.acra.ACRA lib file

**Comment by space2** [comment]
ChkBugReport does not support this format. Try to find help on http://www.acra.ch/ (maybe https://github.com/ACRA/acralyzer)

**Comment by jimandyzgs** [comment]
This is still exist.
java -jar chkbugreport-0.5-215.jar ../battery-historian/bugreporttest.txt 
ChkBugReport 0.5 (rev 215) (C) 2012 Sony Ericsson Mobile Communications AB
Failed to load plugin: com.sonyericsson.chkbugreport.AdbExtension
Loading input...
Loaded in 0.00 seconds.
Not a bugreport file

watching code:

    private Plugin loadPlugin(String className) {
        try {
            Class<?> cls = Class.forName(className);
            return (Plugin)cls.newInstance();
        } catch (Throwable e) {
            printErr(1, "Failed to load plugin: " + className);
            return null;                        // cannot execu.
        }
    }
but the code, cannot found com.sonyericsson.chkbugreport.AdbExtension.
        Plugin adbExt = loadPlugin("com.sonyericsson.chkbugreport.AdbExtension");
        if (adbExt != null) {
            addPlugin(adbExt);
        }

**Comment by jimandyzgs** [comment]
download code, I don't know how to complie it,
I download tools, 
"

    http://sonyxperiadev.github.com/ChkBugReport/download/chkbugreport (Launcher shell script)
    http://sonyxperiadev.github.com/ChkBugReport/download/chkbugreport-0.5-215.jar (The application itself)
"
but I execu it error,  I use battery-historian to analysis bugreporttest.txt is good.
How I use this tool to analysis?
